# Generated by Django 5.1.1 on 2024-09-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='number_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
