# Generated by Django 5.1.1 on 2024-09-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_invoice_number_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='invoice_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='last_year',
            field=models.IntegerField(default=2024),
        ),
    ]
